[package]
name = "smartguard"
version = "0.1.0"
edition = "2021"

[dependencies]
smartguard-crypto = { path = "../smartguard-crypto" }
rustyguard-core = { workspace = true }
rustyguard-tun = { workspace = true }
rustyguard-crypto = { workspace = true }

clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
base64 = "0.22"
rpassword = "7"
secrecy = { workspace = true }
ipnet = "2.9"
iptrie = "0.10"
rand = "0.9"
tai64 = { version = "4.0", features = ["std"] }
tokio = { version = "1", features = ["rt", "net", "io-util", "macros", "time", "signal"] }

[dev-dependencies]
tempfile = "3"
